name: Deploy traderrs

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest

    env:
      REMOTE_USER: b
      REMOTE_HOST: 77.37.96.91
      REMOTE_DIR: /home/b/traderrs
      REMOTE_BIN: /home/b/traderrs/traderrs
      SERVICE_NAME: traderrs.service
      SERVICE_REMOTE_PATH: /etc/systemd/system/traderrs.service

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

#      - name: Save bot state
#        run: curl -s "http://${REMOTE_HOST}:3030/api/v1/bots/state/save"

      - name: Install Rust
        uses: actions-rs/toolchain@v1
        with:
          toolchain: stable
          override: true

      - name: Build release
        run: |
          cargo build --release
          strip target/release/traderrs

      - name: Setup SSH key
        uses: webfactory/ssh-agent@v0.8.0
        with:
          ssh-private-key: ${{ secrets.SSH_PRIVATE_KEY }}

      - name: Prepare remote directory
        run: |
          ssh -o StrictHostKeyChecking=no $REMOTE_USER@$REMOTE_HOST << EOF
            mkdir -p $REMOTE_DIR
          EOF

      - name: Upload binary
        run: |
          scp -o StrictHostKeyChecking=no target/release/traderrs \
              $REMOTE_USER@$REMOTE_HOST:/tmp/traderrs

      - name: Upload service file
        run: |
          scp -o StrictHostKeyChecking=no traderrs.service \
              $REMOTE_USER@$REMOTE_HOST:/tmp/traderrs.service

      - name: Deploy
        run: |
          ssh -o StrictHostKeyChecking=no $REMOTE_USER@$REMOTE_HOST << EOF
#            # Stop old service
#            sudo systemctl stop $SERVICE_NAME || true

            # Move binary
            sudo mv /tmp/traderrs $REMOTE_BIN
            sudo chmod +x $REMOTE_BIN

            # Move service file
            sudo mv /tmp/traderrs.service $SERVICE_REMOTE_PATH
            sudo chmod 644 $SERVICE_REMOTE_PATH

            # Reload systemd + start service
            sudo systemctl daemon-reload
            sudo systemctl enable $SERVICE_NAME
            sudo systemctl restart $SERVICE_NAME

            # Show service status
            sudo systemctl status $SERVICE_NAME --no-pager
          EOF
